version: '3.9'

services:
    mysql:
        image: mysql:8
        container_name: prestashop_mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: prestashop
            MYSQL_ROOT_PASSWORD: prestashop
        ports:
            - 3306:3306
        volumes:
            - ./data/prestashop_db:/var/lib/mysql
        networks:
            - db
    prestashop:
        image: prestashop/prestashop:1.7
        container_name: prestashop
        environment:
            DB_SERVER: mysql
        ports:
            - 80:80
        networks:
            - prestashop
            - db
        volumes:
            - ./data/prestashop:/var/www/html

networks:
    db:
    prestashop: